### ISSUE TITLE
Pressing "Enter" not working for question about using CDS key for `era5cli`

### ISSUE THREAD

**Issue by geek-yang** [eWaterCycle/era5cli#156]
If user tries to use `era5cli` for the first time with cds key only, in the terminal they will be asked

```sh
era5cli configuration file not found. Looking for CDSAPI key.
Valid CDS keys found in the .cdsapirc file. Do you want to use these for era5cli? [Y/n]
```

If user simply presses `Enter` (since capital `Y` always means the default which will be triggered by pressing `Enter`), it doesn't work and will throw an error:

```py
era5cli.key_management.InvalidLoginError: No valid CDS login found. Please configure your CDS login using: 'era5cli config'
```

This is somehow misleading. Pressing `Enter` should be interpreted as `Y` in this case. I checked the source code and it seems this issue relates to this line https://github.com/eWaterCycle/era5cli/blob/750a4d6e7b5d41b92745d596cbcd1208b60428fe/era5cli/key_management.py#L144-L147

This can be fixed simply by adding `""` to the condition, which will look like
`if userinput in ["Y", "y", "Yes", "yes", ""]:`

The whole error message is placed below.

**Comment by geek-yang** [comment]
```sh
~ via 🐍 v3.10.12 (ai4s2s)
❯ era5cli monthly --variables soil_type --startyear 2000 --months 01
era5cli configuration file not found. Looking for CDSAPI key.
Valid CDS keys found in the .cdsapirc file. Do you want to use these for era5cli? [Y/n]
Traceback (most recent call last):
  File "/home/yangliu/venv/ai4s2s/bin/era5cli", line 8, in <module>
    sys.exit(main())
  File "/home/yangliu/venv/ai4s2s/lib/python3.10/site-packages/era5cli/cli.py", line 91, in main
    _execute(args)
  File "/home/yangliu/venv/ai4s2s/lib/python3.10/site-packages/era5cli/cli.py", line 53, in _execute
    era5 = efetch.Fetch(
  File "/home/yangliu/venv/ai4s2s/lib/python3.10/site-packages/era5cli/fetch.py", line 126, in __init__
    self._get_login()  # Get login info from config file.
  File "/home/yangliu/venv/ai4s2s/lib/python3.10/site-packages/era5cli/fetch.py", line 219, in _get_login
    key_management.check_era5cli_config()
  File "/home/yangliu/venv/ai4s2s/lib/python3.10/site-packages/era5cli/key_management.py", line 124, in check_era5cli_config
    raise InvalidLoginError(
era5cli.key_management.InvalidLoginError: No valid CDS login found. Please configure your CDS login using: 'era5cli config'
```
